#!/bin/bash
# kayakfind - A script to find flights on kayak.com using their RSS
# Kayakfind constants
CURRENCY=NZD

# Configurations for the shell script
version=0.0.1
temp_file=temp.xml
log_file=./logs/history.log
xpath_sh=./lib/xpath

getHelp() {
cat <<-EOF
usage:	kayakfind [departure] [destination]
		kayakfind akl syd,mel
EOF
}

getBestPrice() {
  echo "\$$CURRENCY `$xpath_sh $temp_file "//kyk:price/text()" | head -n 1`"
}

getPriceList() {
   $xpath_sh $temp_file "//item/title/text()"
}

if [ "$1" != "" ]; then
	DEPARTURE=$1
fi

if [ "$2" != "" ]; then
	DESTINATION=$2
fi

if [ "$#" -lt 2 ]; then
getHelp;
exit
fi

# Call kayak to find the flights needed
curl -s -o $temp_file "https://www.kayak.com/h/rss/fare?code=$DEPARTURE&tm$TRAVEL_MONTH&dest=$DESTINATION&mc=$CURRENCY"


# Display the result
cat <<-EOF
kayakfind - $version
Searching for flights from $DEPARTURE to $DESTINATION in $CURRENCY

The best price is `getBestPrice;`

`getPriceList;`
EOF