#!/bin/bash

# DO WHAT YOU WANT TO PUBLIC LICENSE 
#                     Version 2, December 2004 
# 
#  Copyright (C) 2004 Filype Pereira <pereira.filype@gmail.com> 
# 
#  Everyone is permitted to copy and distribute verbatim or modified 
#  copies of this license document, and changing it is allowed as long 
#  as the name is changed. 
# 
#             DO WHAT YOU WANT TO PUBLIC LICENSE 
#    TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 
# 
#   0. You just DO WHAT YOU WANT TO. 

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What You Want

# kayakfind - A script to find flights on kayak.com using their RSS

# Kayakfind constants
CURRENCY=NZD

# Configurations for the shell script
version=0.0.2
app_name=$(basename "$0")
file_tmp=$(mktemp -t kayakfind)
file_log=logs/history.log
xpath_sh=libs/xpathPHP/xpathPHP

getHelp() {
cat <<-EOF
usage:	kayakfind [departure] [destination]
		kayakfind akl syd,mel
EOF
}

if [ "$#" -lt 2 ]; then
getHelp;
exit
fi

getBestPrice() {
  echo "\$$CURRENCY `$xpath_sh $file_tmp "//kyk:price/text()" | head -n 1`"
}

getPriceList() {
   $xpath_sh $file_tmp "//item/title/text()"
}

if [ "$1" != "" ]; then
	DEPARTURE=$1
fi

if [ "$2" != "" ]; then
	DESTINATION=$2
fi

# Call kayak to find the flights needed
curl -s -o $file_tmp "https://www.kayak.com/h/rss/fare?code=$DEPARTURE&tm=$TRAVEL_MONTH&dest=$DESTINATION&mc=$CURRENCY"

# Save this request into the log
echo `date` - $@ - `getBestPrice;` >> $file_log

# Display the result
cat <<-EOF
$app_name - $version
Searching for flights from $DEPARTURE to $DESTINATION in $CURRENCY

The best price is `getBestPrice;`

`getPriceList;`
EOF

# Remove temp file at the exit using trap
trap 'rm -f "$file_tmp"' EXIT
